# These are the columns in the vocab table.
# This data structure is required by the numpy ndarray.
# The first value is the name of the field (case sensitive!)
# The second value is the encoding the data in that field. "U" is for unicode, the number marks the max number of characters.

data_type = [("expression", "U100000"),
             ("category", "U20"),
             ("category_2", "U20"),
             ("verb", "U1"),
             ("noun", "U1"),
             ("non_v_pred", "U1"),
             ("frequent", "U1"),
             ("sg", "U1"),
             ("pl", "U1"),
             ("mass", "U1"),
             ("animate", "U1"),
             ("properNoun", "U1"),
             ("finite", "U1"),
             ("bare", "U1"),
             ("pres", "U1"),
             ("past", "U1"),
             ("ing", "U1"),
             ("en", "U1"),
             ("3sg", "U1"),
             ("arg_1", "U100"),
             ("arg_2", "U100"),
             ("arg_3", "U100"),
             ("root", "U20"),
             ("wh_np_verb", "U1"),
             ("responsive", "U1"),
             ("passive", "U1"),
             ("strict_intrans", "U1"),
             ("strict_trans", "U1"),
             ("causative", "U1"),
             ("spray_load", "U1"),
             ("inchoative", "U1"),
             ("agentive", "U1"),
             ("event", "U1"),
             ("adjs", "U100"),
             ("restrictor_DE", "U100"),
             ("scope_DE", "U100"),
             ("NPI", "U1"),
             ("agent", "U1"),
             ("occupation", "U1"),
             ("clothing", "U1"),
             ("appearance", "U1"),
             ("physical", "U1"),
             ("conceptual", "U1"),
             ("breakable", "U1"),
             ("start_with_vowel", "U1"),
             ("frontable", "U1"),
             ("gender", "U1"),
             ("irrpl", "U1"),
             ("special_en_form", "U1"),
             ("irr_verb", "U1"),
             ("document", "U1"),
             ("negated", "U1"),
             ("locale", "U1"),
             ("institution", "U1"),
             ("arg_clause", "U100"),
             ("homophonous", "U1"),
             ("pluralform", "U1000"),
             ("singularform", "U1000"),
             ("sgequalspl", "U1"),
             ("topic", "U1"),
             ("image", "U1"),
             ("v_embed_sc", "U1"),
             ("change_of_state", "U1"),
             ("initial_state", "U1000"),
             ("change_arg", "U1"),
             ("vehicle", "U1"),
             ("vegetable", "U1"),
             ("food", "U1"),
             ("light", "U1"),
             ("liquid", "U1"),
             ("animal", "U1"),
             ("openable", "U1"),
             ("climbable", "U1"),
             ("cleanable", "U1"),
             ("quantifier", "U1"),
            ]

